### ISSUE TITLE
Consider sourcing ~/.pryrc

### ISSUE THREAD

**Issue by binarymason** [technekes/nib#119]
Would be nice if a user's `~/.pryrc` and/or `~/.irbrc` preferences could be included in the docker build.

**Comment by blankenshipz** [comment]
I think this could be achieved but would be problematic if the users `.(irb|pry)rc` referenced code that isn't available inside of the created container. Perhaps this could be properly documented and conditionally enabled by the user.

**Comment by johnallen3d** [comment]
I love the idea of having a more consistent IRB/Pry experience however, I think @blankenshipz concern is valid. I like the idea of this being optional somehow (time to introduce `nib config...`?). Personally my `.(irb|pry)rc`s look fairly harmless, it's worth experimenting with.

**Comment by johnallen3d** [comment]
On second thought, perhaps it's a "premature optimization" to worry about dependencies within a users `~/.pryrc`. That seems to me like a code smell. A pry configuration should be smart enough to work even if a dependency is not present. For example:

[ripped from `skwp/dotfiles`](https://github.com/skwp/dotfiles/blob/master/irb/pryrc#L24-L37)
```rb
# == PLUGINS ===
# awesome_print gem: great syntax colorized printing
# look at ~/.aprc for more settings for awesome_print
begin
  require 'awesome_print'
  # The following line enables awesome_print for all pry output,
  # and it also enables paging
  Pry.config.print = proc {|output, value| Pry::Helpers::BaseHelpers.stagger_output("=> #{value.ai}", output)}

  # If you want awesome_print without automatic pagination, use the line below
  # Pry.config.print = proc { |output, value| output.puts value.ai }
rescue LoadError => err
  puts "gem install awesome_print  # <-- highly recommended"
end
```
