### ISSUE TITLE
Consider additional shells for the `shell` command

### ISSUE THREAD

**Issue by johnallen3d** [technekes/nib#126]
Some users are installing `zsh` (`fish`?) inside of images. It should be fairly trivial to add support for additional shell to the [`shell` command startup script](https://github.com/technekes/nib/blob/master/lib/nib/shell.rb#L5-L13). Said script could likely be refactored to reduce duplication as well.

**Comment by blankenshipz** [comment]
Perhaps it might be better to support a `bin/shell` user override like we do with `bin/console` that would keep us from having to maintain a list of shell's and order of preference

Of course  you could argue that `zsh` is reasonable to have in the list of supported defaults

**Comment by johnallen3d** [comment]
Good point, I think `bin/shell` would be a nice improvement and consistent with the `console` command. I also think `zsh` is common enough that it warrants adding.
