### ISSUE TITLE
Error parsing environment variables 

### ISSUE THREAD

**Issue by blankenshipz** [technekes/nib#134]
After upgrading from `nib` `1.4.2` to `1.5.0`:

There seems to be an issue with environment variables that contain backslashes: 

```
ERROR: Invalid interpolation format for "environment" option in service "web": "d\xC7\xC7"
```

**Comment by johnallen3d** [comment]
Thanks for the feedback. Do you mind providing the `docker-compose` config (or the relevant portion) that is causing the issue?

**Comment by blankenshipz** [comment]
@johnallen3d I think the relevant part would be:

```yml
environment:
      ENCRYPTION_KEY: d\xC7\xB1<\xD07\xD0G\x19\x85\xC6T\xBB\x8D\x98\x05\xB8\xF7\xCA\xFF\x83J\x19_\xFBf&:\xFEY$\xE7
```

**Comment by johnallen3d** [comment]
Thanks! I tried something simple like the following but couldn't reproduce. ☝️ does the trick though!

```yaml
    environment:
      FOO: B\A\R
```
