### ISSUE TITLE
Consider adding rspec

### ISSUE THREAD

**Issue by blankenshipz** [technekes/nib#27]
We already have support for things like `rake` `guard` `bundle`, perhaps we should add `nib rspec`.

What are your thoughts @johnallen3d?

**Comment by johnallen3d** [comment]
Agreed, I think I've found myself doing that as well. Although I usually set the default rake task to run RSpec and RuboCop so `nib rake app` is better ultimately.

**Comment by blankenshipz** [comment]
I opened the PR, I think it's good to have the option? I think it's good for `nib` to cover most of the `ruby`/`rails` tooling.

**Comment by johnallen3d** [comment]
Added by #28.
