### ISSUE TITLE
setup command looking for bin/bootstrap

### ISSUE THREAD

**Issue by blankenshipz** [technekes/nib#71]
The setup command is [looking for bin/bootstrap](https://github.com/technekes/nib/blob/master/bin/setup#L12) should this be changed to `bin/setup`? ditto for `.before` and `.after`

**Comment by blankenshipz** [comment]
looking into this further it looks like the version of rails that I'm using has a default setup script in `bin/setup` which may not be what we intend to execute as default behavior

@johnallen3d thoughts?

```RUBY
#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  # This script is a starting point to setup your application.
  # Add necessary setup steps to this file.

  puts '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') or system!('bundle install')

  # puts "\n== Copying sample files =="
  # unless File.exist?('config/database.yml')
  #   cp 'config/database.yml.sample', 'config/database.yml'
  # end

  puts "\n== Preparing database =="
  system! 'bin/rails db:setup'

  puts "\n== Removing old logs and tempfiles =="
  system! 'bin/rails log:clear tmp:clear'

  puts "\n== Restarting application server =="
  system! 'bin/rails restart'
end
```

**Comment by johnallen3d** [comment]
Ugh, re: still looking for `./bin/bootstrap{.before,.after}`! That's a hotfix in the making!

Regarding the Rails default, I think that's pretty reasonable. What about it is not working for you?

**Comment by blankenshipz** [comment]
It doesn't seem to setup the test db? I could be missing something

**Comment by johnallen3d** [comment]
Looks like it's a baseline that you are intended modify.

>   # This script is a starting point to setup your application.
>   # Add necessary setup steps to this file.

**Comment by blankenshipz** [comment]
I see! thanks 👍
