### ISSUE TITLE
Consider --no-deps for Certain Commands

### ISSUE THREAD

**Issue by johnallen3d** [technekes/nib#74]
Some of the wrapped commands do not require service dependencies (databases) to be running in order to function. For example `nib bundle web` would not need postgres running to work.

Likely candidates:

* bundle
* codeclimate
* rubocop

The proposal would be to add something to [commands configuration](https://github.com/technekes/nib/blob/master/config/commands.json) to indicate this and to have [./bin/wrap_command](https://github.com/technekes/nib/blob/master/bin/wrap_command) respect that by passing `--no-deps` to `docker-compose run`. Or perhaps the change to configuration would be an `arguments` key that is used in composing the command.

**Comment by blankenshipz** [comment]
Sounds good to me!

**Comment by johnallen3d** [comment]
It would appear that this change was lost in the transition to the current (Ruby) implementation.

**Comment by johnallen3d** [comment]
`debug` should also [have `--no-deps`](https://github.com/technekes/nib/blob/master/lib/nib/debug.rb#L19) set automatically. If so it would not need to re-define `#script`.
