### ISSUE TITLE
Reliance on the existence of `/usr/src/app`

### ISSUE THREAD

**Issue by jackross** [technekes/nib#78]
It appears that `nib` relies on the existence of `/usr/src/app` in several places (especially `*_history` files).  Should this be the case?  It seems weird to me that gem authoring, for instance, should use an `app` directory, but I'm OK with it if that's the convention...

**Comment by jackross** [comment]
For example: https://github.com/technekes/nib/blob/333613875eca7fef1cf56692677d65b1d0926d77/bin/console#L19

**Comment by johnallen3d** [comment]
The only reason for the path `/usr/src/app` is that it's what the official `ONBUILD` Docker Ruby image [defines as a `WORKDIR`](https://github.com/docker-library/ruby/blob/1b08f346713a1293c2a9238e470e086126e2e28f/2.3/onbuild/Dockerfile#L7). I think it's reasonable for `nib` not to care about that.

Searching the codebase it seems the only relavant places that use that path are for history files. I'll take a look at using a relative path in those cases and submit a PR if that works out.

```sh
❯ ag "/usr/src/app"

bin/_tty
18:  -e HISTFILE=/usr/src/app/tmp/shell_history \

bin/console
19:IRB.conf[:HISTORY_FILE] = \"/usr/src/app/tmp/irb_history\"
23:Pry.config.history.file = \"/usr/src/app/tmp/irb_history\"
```
