### ISSUE TITLE
Support `--service-ports` Option of `docker-compose run`

### ISSUE THREAD

**Issue by johnallen3d** [technekes/nib#89]
As stated in #75 the `--service-ports` option of `docker-compose run` would be useful for those wanting to use a non-remote debugger in an app (eg. `binding.pry` in a Rails app). Currently no switches or flags are supported. Consider adding a switch to the `run` command to support this.

**Comment by blankenshipz** [comment]
@johnallen3d Would it be possible to generalize this idea and provide the ability to pass arbitrary commands to run?

**Comment by johnallen3d** [comment]
I've taken an initial stab at it with #90 but it's not quite so straight foward as you might want. See the #90 for further details. Feedback encouraged! 😄

**Comment by johnallen3d** [comment]
Resolved via #91.
